### ISSUE TITLE
UI enhancement

### ISSUE THREAD

**Issue by Bhum-ika** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#105]
![image](https://github.com/user-attachments/assets/875cce83-13a3-41df-a7ac-7cbf0da4f123)

After appearance of invalid Details, proper styling is not provided due to which some part of "Create Account" button is getting hidden

![Screenshot 2024-10-13 103429](https://github.com/user-attachments/assets/8204d0d5-0787-4aad-a23c-0ca40d202523)

Added credentials should be in popped up colors,to show a difference in placeholder and actual values

Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by AkshitLakhera** [comment]
@Bhum-ika  go ahead

**Comment by anchalchaturvedi08** [comment]
I want to work on this, can you assign me this task?
