### ISSUE TITLE
[Feature] Show/Hide Password Option for Signup and Login

### ISSUE THREAD

**Issue by DevanshS9881** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#108]
### Overview:
 I would like to propose the addition of a "Show/Hide Password" feature for both the signup and login forms on the website. This  enhancement will improve user experience and accessibility by allowing users to see the password they are entering, helping to prevent errors and reduce frustration.

### Details:

-         I would like to add a  toggle button (eye icon) next to the password input field that users can click to switch between visible and masked password text.
-         The button should clearly indicate the current state (show/hide) to prevent confusion.

**Comment by DevanshS9881** [comment]
It would be great if you assign this issue to me under GSSoC extd and hactoberfest accepted label.I would be eager to work on this issue.

**Comment by AkshitLakhera** [comment]
@DevanshS9881  you can proceed

**Comment by sameer-soni** [comment]
@AkshitLakhera if there is no update, can i get assigned?
