### ISSUE TITLE
Height of Landing Page

### ISSUE THREAD

**Issue by jainaryan04** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#111]
you need to scroll down on the homepage to login. I want to fix the height of the landing page to size of viewport to enhance UI.
@AkshitLakhera 
please add gssoc-ext and hacktoberfest-accepted labels

![image](https://github.com/user-attachments/assets/2eeaf386-d49f-45f1-ac18-238f64cd440f)

**Comment by AkshitLakhera** [comment]
@jainaryan04  go ahead
