### ISSUE TITLE
[Documentation]  :  Wanted To Add Contributing.md

### ISSUE THREAD

**Issue by milansamuel609** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#138]
I wanted to add the contributing.md file which will help the contributors to easily contribute. It will also help them understand the correct way of following coding practices and other important things.

Wanted to do the following changes :-

1) Enhance the project structure
2) Add code of conduct section
3) Add star our repository section
4) Add need help with the basics section
5) Add first pull request steps section
6) Add additional method of contributing through GitHub desktop section
7) Add good coding practices section
8) Add the pull request rules section
9) Add the thank you section

**Comment by AkshitLakhera** [comment]
@milansamuel609  it is already there

**Comment by milansamuel609** [comment]
> @milansamuel609 it is already there

Actually I have not seen it just saw the Readme.md file. But no issue 👍 .
