### ISSUE TITLE
UPDATION IN README FILE REQUIRED 

### ISSUE THREAD

**Issue by soham0028** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#140]
Hello @AkshitLakhera 
the current readme file lacks proper structure and does not contain: 
1. featured in section 
2. table of contents for easy navigation 
3. forkers and sgtargazers section 
4. back to top button 
 kindly assign me the issue under gssoc-extd labels so my work counts under these events

**Comment by AkshitLakhera** [comment]
@soham0028  it is pretty fine no  need to work on it , if you can contribute somewhere  else go ahead with it
