### ISSUE TITLE
Blog Section Redesign

### ISSUE THREAD

**Issue by dev129** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#143]
**Issue Title:** Blog Section Design Enhancement for Theming Consistency

**Description:**
Hi @AkshitLakhera,

I’d like to redesign the Blog section of Pencraft to better align with the website's overall theme. My goal is to create a visually cohesive and engaging layout that enhances user experience while keeping in line with the platform’s aesthetic and branding.

Please let me know if there are any specific guidelines or elements you’d like me to incorporate.

**Comment by AkshitLakhera** [comment]
@dev129  start working assigning to you

**Comment by dev129** [comment]
https://github.com/user-attachments/assets/97d9b36f-788c-40fa-b6aa-68faf11f7720

Hi , I have added the search functionality in the blog section, along with parallax effect for images, proper icons , expandable read more link for long description, headings for quick sorting .  The design is responsive for all screen sizes.

**Comment by dev129** [comment]
Hi @AkshitLakhera , I have designed the blog section to a premium level, let me know your thoughts on this.

**Comment by dev129** [comment]
Hi @AkshitLakhera , what do you think about it

**Comment by dev129** [comment]
Hi @AkshitLakhera , what are your final thoughts on this ?

**Comment by dev129** [comment]
Hi @AkshitLakhera , are you still interested or not ?

**Comment by dev129** [comment]
Hi @AkshitLakhera , do you like the blog section design ?

**Comment by AkshitLakhera** [comment]
@dev129 yes I am interested you can make pr.
