### ISSUE TITLE
FAQ section

### ISSUE THREAD

**Issue by dev129** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#145]
**Issue Title:** Design Update for FAQ Section to Align with Website Theme

**Description:**
Hi @AkshitLakhera,

I would like to revamp the FAQ section to better match Pencraft's website theme, enhancing both visual consistency and user experience. My aim is to create a cohesive and engaging design that fits seamlessly with the site's aesthetic.

Let me know if you have any specific design preferences or content layout ideas you'd like me to consider for the update!

**Comment by AkshitLakhera** [comment]
@dev129  go  ahead work  on it
