### ISSUE TITLE
Ui: make the whole homepage responsive

### ISSUE THREAD

**Issue by AE-Hertz** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#146]
I will make the whole page responsive, here is the screenshot to Demonstrate current situation. 
![1000016687](https://github.com/user-attachments/assets/8f85717f-38b5-45ad-9dd3-15848508412e)

Assign me this issue, under hacktoberfest and gssoc-ext.

**Comment by AkshitLakhera** [comment]
@AE-Hertz  go ahead

**Comment by AE-Hertz** [comment]
@AkshitLakhera i am done making it , requested a PR, thank you
