### ISSUE TITLE
Adding A Navbar 

### ISSUE THREAD

**Issue by satyam969** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#161]
a navigation bar (navbar) to improve the user experience on the website by providing clear, accessible links to different sections. A well-designed navbar will make the site more intuitive, allow users to quickly find essential pages, and enhance overall usability.
![Screenshot 2024-11-05 145451](https://github.com/user-attachments/assets/e60aaa95-9655-4e19-bf62-b69a6f7f49fb)

woud like to take this assignment

**Comment by AkshitLakhera** [comment]
@satyam969  we already have navbar inside application we don't need it  here
