### ISSUE TITLE
[FEAT] : Design Eye-Catching Progress Bar on scroll, design the scroll bar and add a Back to top button for UI Aesthetics

### ISSUE THREAD

**Issue by Edasgh** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#165]
:red_circle: Add a progress bar and a back to top button in all the pages
:red_circle: **Enhancement Aim** : I propose the development of a visually appealing progress bar , a scroll bar and a back to top button that seamlessly integrates with the overall UI aesthetics of the application.
:red_circle: **Changes** :
- Enhanced Usability: A visually appealing progress bar helps users understand their progress within a task or process, and a back to top button helps users to go back to the top-part improving usability and navigation.

- Improved Aesthetics: Customizing the  progress bar and the back to top button to match the UI enhances the overall look and feel of the application, making it more attractive to users.

- Increased User Engagement: An engaging and cohesive interface can lead to higher user satisfaction, encouraging them to interact more with the application.

Please assign this issue to me under gssoc-ext, hacktoberfest-accepted and a relevant level labels

**Comment by AkshitLakhera** [comment]
@Edasgh  go ahead.
