### ISSUE TITLE
SignUp/SignIn flow is buggy.

### ISSUE THREAD

**Issue by kushagra0304** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#20]
SignUp/SignIn flow is buggy.

Does not work as intended.

**Comment by kushagra0304** [comment]
I have worked with JWT auth flow and I am confident I can streamline the flow. Can this be please assigned to me.

**Comment by AkshitLakhera** [comment]
Hey @kushagra0304 ,
I have seen  someone is working on auth part in issue #18 . I am assigning this issue to you ,but I want you to coordinate with him to streamline this process.And in between if you need any help ,I am always here.
All the  best :)

**Comment by kushagra0304** [comment]
I believe it may be difficult to coordinate with two other people on this feature set. Could you please assign this issue to someone else? I will look for another issue to contribute to.
