### ISSUE TITLE
BUG : There is no loading  and error in the sign in and sign up page 

### ISSUE THREAD

**Issue by UmeshKumar0143** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#24]
Issue : 
There is no loading in the sign in and sign up page so the user doesn't know if something is happening or not and user doesn't get any error if anything is wrong  

Expected behaviour: 
There should be some kind of loading when the user clicks on sign in or sign up and user should get  a issue  if something is wrong 

How to recreate: 
-Go to sign in or sign up page 
-Fill the details and click on sign in or sign up button 

Video showing the issue : 

https://github.com/user-attachments/assets/0489c933-2e2d-4106-b875-2bcc5546713f

**Comment by AkshitLakhera** [comment]
Yes it is nice to have loading and error in auth  pages.Go ahead.I am  assigning this issue to you.Feel free to reach me if you need any help from me.
All the best :)

**Comment by UmeshKumar0143** [comment]
@AkshitLakhera  about the error message should i use toastify for error message or make a simple div for error message

**Comment by AkshitLakhera** [comment]
> @AkshitLakhera about the error message should i use toastify for error and sucess message or make a simple div for error message

Yes you can go with toastify and make it look sleek and clean.

**Comment by UmeshKumar0143** [comment]
@AkshitLakhera  added toastify error and sucess are these ok ? 

Uploading 2024-10-02 19-33-17.mp4…

**Comment by UmeshKumar0143** [comment]
@AkshitLakhera added toastify error and sucess are these ok ?


https://github.com/user-attachments/assets/5e46f359-9c76-4d08-a102-6813f2123223
