### ISSUE TITLE
Addition of forget password option on signin (Backend and frontend both)

### ISSUE THREAD

**Issue by Sourabh782** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#25]
I wanted to implement a new functionality, where users can reset their password if forgotten, currently theres no way to login if we forget password
![Screenshot 2024-10-02 115322](https://github.com/user-attachments/assets/5b6b0cae-2901-4142-8e3b-b2dbb12138f3)

**I wanted to contribute to this issue under gssoc-extd and hacktober**

**Comment by AkshitLakhera** [comment]
Hey @Sourabh782 , 
I have some other guys working on  signup/signin thing in issue #18  and #20 .I want you to work with them will assign you three that issue under #18 issue .

**Comment by Sourabh782** [comment]
Sure @AkshitLakhera, i'll join with them
