### ISSUE TITLE
[Frontend] Use Lenis for Smooth Scrolling

### ISSUE THREAD

**Issue by iamDyeus** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#26]
I propose integrating [Lenis](https://github.com/darkroomengineering/lenis) to enhance the smooth scrolling experience across the entire web application. This will provide a more fluid and polished scrolling effect compared to the default browser behavior.

### Benefits:
- Improved user experience with smoother, more natural scrolling
- Consistent scroll behavior across different devices and browsers

### Action:
- Add Lenis as a dependency
- Replace default scroll behavior with Lenis throughout the app

**Comment by AkshitLakhera** [comment]
Yes ,it is nice add on to have .Go ahead ,I am assigning to you.Feel free to reach me if you need any help.
All the best :)

**Comment by iamDyeus** [comment]
@AkshitLakhera  I'm currently stuck with some work. I'll start working on this from the 12th of October. Does that sound good to you?

**Comment by AkshitLakhera** [comment]
@iamDyeus  okay no worries
