### ISSUE TITLE
FEATURE: Automated Greeting Workflow

### ISSUE THREAD

**Issue by samyak-aditya** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#27]
I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository. The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.

Hey @AkshitLakhera please assign me this task with labels "gssoc-ext" and "level1"

**Comment by AkshitLakhera** [comment]
sure ,go ahead.
