### ISSUE TITLE
Feature Request: Update the Blog Navbar Search Functionality when The Blogs are Opened

### ISSUE THREAD

**Issue by Siddhi-sahu** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#31]
Issue Description:
The search bar in the blog's navbar (when viewing a specific blog) does not perform any actions when a user types into it. It should be updated to allow users to search for specific parts of blog posts based on entered keywords.

Steps to Reproduce:
1). Open the blog's website.
2). Click on any blog.
3). Type any text into the search bar in the navbar.
4). Observe that no search results are displayed or filtered as expected.

Expected Behavior:
The search bar should filter or display results based on the user's input. For example, as the user types, relevant parts of the blog should appear.

Hey @AkshitLakhera please assign me this task with appropriate labels:) i will implement the search functionality so user can easily navigate to parts of long blogs to save time 

![Screenshot 2024-10-02 190659](https://github.com/user-attachments/assets/95a26914-22b4-4ba3-b2f3-1a74fdec7708)

**Comment by AkshitLakhera** [comment]
Definitely it is nice  feature to have.Go ahead ,I am assigning this to you.Feel free to reach me if you need any help.
Looking forward to it.
