### ISSUE TITLE
BUG: Hardcoded Name in the comment section and comment is not shown after commenting 

### ISSUE THREAD

**Issue by UmeshKumar0143** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#36]
Issue  : The name of the commenter is Hardcoded in the comments tab  and the comment of the person is not shown after commenting we need to close the tab and again open it to see the comment . 

https://github.com/user-attachments/assets/f8d9b108-87b6-4a04-be70-9c0dd01ebea7

Steps to reproduce : 
- Go to any blog post 
- open comment section 
- check the name of the commenter 
- make a comment 

Expected Behaviour: The name should be of the person commenting or logged in . 
And the comment should be shown after clicking on respond

**Comment by AkshitLakhera** [comment]
Yes it is nice add on to have , go ahead.
