### ISSUE TITLE
UI/UX: The text is not clearly visible on sign in and sign up page 

### ISSUE THREAD

**Issue by UmeshKumar0143** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#40]
Issue : 
The text on the right side of the sign in and sign page is not clearly visible due to the background

![image](https://github.com/user-attachments/assets/9d99b372-98cb-4328-817e-3d284426a0c6)
![image](https://github.com/user-attachments/assets/f5de3967-df6f-4c82-92e7-0591e8ab3b90)

expected Behaviour: 
The text should be properly  readable to the user  the text color should be changed to  blend properly with the background

**Comment by AkshitLakhera** [comment]
Go ahead , with this.I will assign you.
