### ISSUE TITLE
add code_of_conduct.md

### ISSUE THREAD

**Issue by kartikey369-ind** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#43]
i want to work on this please add gssoc extd and hacktoberfest lable

**Comment by rahulgithub-web** [comment]
@AkshitLakhera CODE_OF_CONDUCT.md file is created. Please accept the pull request.

**Comment by kartikey369-ind** [comment]
Iam sorry to say but my time is wasted right I started working on it...

**Comment by kartikey369-ind** [comment]
@AkshitLakhera please respond to this the issue is mine

**Comment by AkshitLakhera** [comment]
> @AkshitLakhera please respond to this the issue is mine

okay kartikey you raised issue first ,so I am going with you. Raise pr

**Comment by AkshitLakhera** [comment]
> > @AkshitLakhera please respond to this the issue is mine
> 
> okay @kartikey369-ind kartikey you raised issue first ,so I am going with you. Raise pr. @rahulgithub-web why you have made pr ,when you haven't raised any issue?
If this is way you will move forward  I will not  assign any issue to you.

**Comment by rahulgithub-web** [comment]
@AkshitLakhera sorry for the inconvenience. Next time I will keep this in mind and it won't get repeated.

**Comment by kartikey369-ind** [comment]
done https://github.com/AkshitLakhera/PenCraft-Full-Stack-Blogging-Application/pull/50
