### ISSUE TITLE
Add MIT License to the Repository

### ISSUE THREAD

**Issue by rahulgithub-web** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#44]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Please add an **MIT License** file to the repository. This will clarify the licensing terms and allow potential contributors to understand the usage rights and permissions associated with the project.

### Suggested Change

Add a LICENSE file containing the standard MIT License text to the root directory of the repository.

### Rationale

Having a clear license file is important for open-source projects as it communicates how the project can be used, modified, and shared. The MIT License is a permissive license that encourages open collaboration, and it will help the project attract more contributors. It is a common best practice to include a license file in open-source repositories.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by rahulgithub-web** [comment]
@AkshitLakhera Could you please assign this task to me and add the following labels: `hacktoberfest`, `enhancement`, `documentation`, and `hacktoberfest-accepted`? Thank you!

**Comment by AkshitLakhera** [comment]
Go ahead,I am assigning to you.
