### ISSUE TITLE
Feature: Add scroll to top button 

### ISSUE THREAD

**Issue by shubhagarwal1** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#55]
Websites blog page, currently do not have a scroll to top button which can we time taking for user when number of blogs increases on the page, i will add a scroll to top button on blogs page and dedicated blog page for imporving user experice 
Hey @AkshitLakhera  please assign this task to me

**Comment by AkshitLakhera** [comment]
Go ahead with this,I am assigning to you , Feel free to reach me if needed.
