### ISSUE TITLE
BUG: Prevention of Special characters in signup form and login form with addition of password vie toggle button

### ISSUE THREAD

**Issue by pand-coder** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#59]
Hello @AkshitLakhera 

### ISSUE
The form validation of signup and Login pages is not proper according to the secure coding standards as they should not special characters like  !,<,>,",== these all as it would lead to client side injection attacks and make your website compromised. 
password view toggle button (also known as a "show/hide password" feature) to your form can encourage . 

### Correction
I would like to go through the  codebase to correct form validation which is a alert function which would warn and not allow user to enter special characters in the form and also password view toggle button. 

![Screenshot 2024-10-04 225424](https://github.com/user-attachments/assets/fbdae65b-968b-4f19-ba23-b34a4ebd2638)
![Screenshot 2024-10-04 225742](https://github.com/user-attachments/assets/040ef65f-8c71-4ab6-939c-0b7f70bce1cb)
![image](https://github.com/user-attachments/assets/1bf5ffa8-d74b-43d8-9a96-e20263fbf1f3)

**Comment by AkshitLakhera** [comment]
Hey @pand-coder ,
Go ahead ,I am assigning this issue ti you ,feel free to reach me  if needed .

**Comment by pand-coder** [comment]
Hello @AkshitLakhera  
Thank you for assigning this issue to me and i have started working on it i would like to know how to test the code after the changes made locally.
