### ISSUE TITLE
BUG: The Number of  Comments remains Fixed to 4

### ISSUE THREAD

**Issue by UmeshKumar0143** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#60]
Issue :
The number of Coments is fixed and doesn't change according to the number of comments 

![image](https://github.com/user-attachments/assets/f5f07354-2014-4ed5-b6ba-2b6d1f47806f)

![image](https://github.com/user-attachments/assets/cab66d98-0df9-4dc1-9aec-0b1b16ebcebf)

Expected Behaviour : 
The number of comments should be equal to the actual number of comments

**Comment by AkshitLakhera** [comment]
I am assigning to you .
