### ISSUE TITLE
BUG: The Blog post is not responsive for mobile devices 

### ISSUE THREAD

**Issue by UmeshKumar0143** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#62]
Issue :
The Blog is not responsive for small devices the text overlaps and doesn't look good 

![image](https://github.com/user-attachments/assets/08fdd3f5-ba57-4fe5-8792-7e9473ca902b)

Steps to recreate 
- Open Pen Craft on mobile devices
- Open any blog post 

Expected Behaviour : 
The website should be responsive on all devices

**Comment by AkshitLakhera** [comment]
Go ahead, I am assigning to you.
