### ISSUE TITLE
Improve UI of Sign-In Page and Enhance Color Contrast

### ISSUE THREAD

**Issue by IshaRawat7** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#65]
The current design of the sign-in page can be improved for better usability and visual appeal.
Here are few suggestions:
Revamp the design elements to create a more visually appealing sign-in page.
Improve the color contrast to ensure better readability and accessibility for all users.
Add animations or images to the right side of the sign-in page to make it more engaging.
![Screenshot 2024-10-05 101939](https://github.com/user-attachments/assets/6d588e04-109c-41cd-ba01-29d5cf86a164)
Hey, @AkshitLakhera  I would like to work upon this.

**Comment by AkshitLakhera** [comment]
Hey @IshaRawat7  ,
Someone is working on this ,he is  almost done with this part.After merging his pr you can take a look and can suggest some add on if you feel.Till then explore ui inside the application,see if you can contribute.

**Comment by IshaRawat7** [comment]
Okay, I will have a look afterwards.
