### ISSUE TITLE
Add Contributors in Readme.md

### ISSUE THREAD

**Issue by sakshamsaraf23** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#66]
It lacks Contributors Profiles in Readme.md

It should be Like the image that I have shared

![373815323-76171289-5b05-48c4-a5be-dc8ac76d70cb](https://github.com/user-attachments/assets/bae873a7-b393-4ba9-9773-b01bce278d8a)

@AkshitLakhera can you assign me this issue under GSSoC-Extd and Hacktoberfest so that I can raise a PR.

I will add this type of Live Contributor Profile Photos in it

**Comment by AkshitLakhera** [comment]
@sakshamsaraf23  Go ahead,I am assigning to you.
