### ISSUE TITLE
Update UI for No Blogs Found Message on /myblogs Page

### ISSUE THREAD

**Issue by Cleveridiot07** [AkshitLakhera/PenCraft-Full-Stack-Blogging-Application#95]
**Description:**
The current UI for the /myblogs page does not effectively communicate when no blogs are found.

**Suggested Changes:**
Design an improved message or component to clearly indicate "No blogs found."
Ensure the message is styled to fit the overall theme of the application.

Hey @AkshitLakhera Please assign this issue to me under hactoberfest2024 and gssoc-ext tags

**Comment by AkshitLakhera** [comment]
@Cleveridiot07 go ahead , I am assigning to you.

**Comment by AkshitLakhera** [comment]
@Cleveridiot07  Are you able to sign in   in application ?

**Comment by Cleveridiot07** [comment]
I’m currently unable to sign in to the application. Could you please provide a test username and password if available?
